//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public int OrderID { get; set; }
        public string Destination { get; set; }
        public string Source { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<System.DateTime> DateSpam { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
