//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseReply
    {
        public int ReplyID { get; set; }
        public Nullable<int> ResponseID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> DateSpam { get; set; }
        public string status { get; set; }
    
        public virtual Response Response { get; set; }
    }
}
