//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Courier.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public string TrackID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> CurrentLocationID { get; set; }
    
        public virtual CurrentLocation CurrentLocation { get; set; }
        public virtual destination destination { get; set; }
        public virtual Order Order { get; set; }
        public virtual Source Source { get; set; }
    }
}
